### ISSUE TITLE
GitHub action to regularly update MondayFights tournaments

### ISSUE THREAD

**Issue by Bebul** [Bebul/MondayFight#11]
Tady tohle https://docs.github.com/en/actions

**Cíle:**
 * mít akci, kterou lze spustit ručně, aby aktualizovala zdrojáky s json daty turnaje
 * tutéž akci naplánovat, aby se spustila vždy v pondělí ve 21:45

**Comment by Bebul** [comment]
viz https://github.com/marketplace/actions/github-commit-push

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        ...
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

takže udělat _**checkout --> run něco, co udělá změny --> push**_ je běžné.
Půjde jen o to, jak udělat ty změny. Umím to v tom javascript, ale ten běží na browseru a těžko udělá save. Nejspíš tedy přes node.js, snad půjde použít stejný kód.
