### ISSUE TITLE
Developer tools on Android Chrome + look at PgnViewer

### ISSUE THREAD

**Issue by Bebul** [Bebul/MondayFight#9]
See https://github.com/mliebelt/PgnViewerJS/issues/180#issue-738492912

I am trying to use Chrome developer tools for Android chrome, through USB connection to desktop with chrome.
But it does not work so far, I have Samsung Galaxy A40.
 * chrome://inspect/#devices
![image](https://user-images.githubusercontent.com/9265147/98537391-7bee2280-2289-11eb-871d-d199eeff4a49.png)
 * remote debugging https://developers.google.com/web/tools/chrome-devtools/remote-debugging?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3

## TODO:
Troubleshooting: I must install drivers USB https://stackoverflow.com/a/22028058/355581

**Comment by Bebul** [comment]
After:
 1. installing USB driver from: http://developer.samsung.com/android/tools-sdks/Samsung-Andorid-USB-Driver-for-Windows
 2. installing: single ADB package required https://forum.xda-developers.com/showthread.php?t=2317790
    + running `d:\Program Files\Minimal ADB and Fastboot>adb.exe devices`
```
List of devices attached
R58N212YQ4K     device
```
 3. opening `chrome://inspect/#devices`

![image](https://user-images.githubusercontent.com/9265147/98539159-25ceae80-228c-11eb-939f-f2490827f41c.png)

**Comment by Bebul** [comment]
It tries to open https://mliebelt.github.io/PgnViewerJS/js/pgnv-assets/46c4b3a96cc14795302cad7319d0ca3d.svg

**Comment by Bebul** [comment]
I have changed svg rook into some different url
```css
.merida cg-board piece.rook.black {
    background-image: url(https://duolingo-images.s3.amazonaws.com/avatars/182263790/pb1gPa8YIl/medium);
}
```
![image](https://user-images.githubusercontent.com/9265147/98541721-2a956180-2290-11eb-984e-48718f4b5961.png)

Also full path to original svg image works
```css
.merida cg-board piece.knight.black {
    background-image: url(https://mliebelt.github.io/PgnViewerJS/js/pgnv-assets/46c4b3a….svg);
}
```
![image](https://user-images.githubusercontent.com/9265147/98542299-f8d0ca80-2290-11eb-98f0-cc398269e49e.png)
